/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alertnusa.view;
import com.alertnusa.view.admBencanaPanel;
/**
 *
 * @author edy
 */
public class AdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        this.setSize(420,720);
        setLocationRelativeTo(null);
        
        adminCardPanel.add(new AdminPanel(), "adminPanel");
        adminCardPanel.add(new admKontenPanel(), "kontenPanel");
        adminCardPanel.add(new admUserPanel(), "userPanel");
        
        java.awt.CardLayout cl = (java.awt.CardLayout) adminCardPanel.getLayout();
        cl.show(adminCardPanel, "adminPanel");
    }
    public void panggilLayar(String namaCard) {
            // Asumsi 'mainPanel' adalah variabel JPanel utama abang yang menggunakan CardLayout
            java.awt.CardLayout cl = (java.awt.CardLayout) adminCardPanel.getLayout();
            cl.show(adminCardPanel, namaCard);
            
            if (namaCard.equals("beritaPanel")) {
            if (admBencanaPanel != null) {
                admBencanaPanel.loadDataBerita(); // Fungsi kueri database berita
            }
        }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminCardPanel = new javax.swing.JPanel();
        adminPanel1 = new com.alertnusa.view.AdminPanel();
        admBencanaPanel = new com.alertnusa.view.admBencanaPanel();
        admKontenPanel1 = new com.alertnusa.view.admKontenPanel();
        admUserPanel1 = new com.alertnusa.view.admUserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        adminCardPanel.setPreferredSize(new java.awt.Dimension(420, 720));
        adminCardPanel.setLayout(new java.awt.CardLayout());

        adminPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanel1MouseClicked(evt);
            }
        });
        adminCardPanel.add(adminPanel1, "dashboardAdmin");
        adminCardPanel.add(admBencanaPanel, "beritaPanel");
        adminCardPanel.add(admKontenPanel1, "kontenPanel");
        adminCardPanel.add(admUserPanel1, "userPanel");

        getContentPane().add(adminCardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alertnusa.view.admBencanaPanel admBencanaPanel;
    private com.alertnusa.view.admKontenPanel admKontenPanel1;
    private com.alertnusa.view.admUserPanel admUserPanel1;
    private javax.swing.JPanel adminCardPanel;
    private com.alertnusa.view.AdminPanel adminPanel1;
    // End of variables declaration//GEN-END:variables
}
