/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;
import com.alertnusa.view.TambahKatalogDialog;
/**
 *
 * @author edy
 */
public class admKontenPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form DashboardPanel
     */
    public admKontenPanel() {
        initComponents();
    }
    
    public void loadDataAdmin() {
        listKontenKatalog.removeAll();
        listKontenKatalog.setLayout(new javax.swing.BoxLayout(listKontenKatalog, javax.swing.BoxLayout.Y_AXIS));

        String query = "SELECT id, disaster_name, description, category, risk_level FROM disasters ORDER BY id ASC";

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query); java.sql.ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("disaster_name");
                String deskripsi = rs.getString("description");
                String kategori = rs.getString("category");

                ItemKatalogBencanaAdminPanel kartu = new ItemKatalogBencanaAdminPanel(id, nama, deskripsi, kategori, this);
                listKontenKatalog.add(kartu);
                listKontenKatalog.add(javax.swing.Box.createVerticalStrut(10));
            }

        } catch (java.sql.SQLException e) {
            System.err.println("Gagal memuat katalog: " + e.getMessage());
        }

        listKontenKatalog.revalidate();
        listKontenKatalog.repaint();
        jScrollPaneKatalog.revalidate();
        jScrollPaneKatalog.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        pilihanKonten = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        btnSOS = new javax.swing.JButton();
        mainContainerAdmin = new javax.swing.JPanel();
        jScrollPaneKatalog = new javax.swing.JScrollPane();
        listKontenKatalog = new javax.swing.JPanel();
        jScrollPaneSOS = new javax.swing.JScrollPane();
        listKontenSOS = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(420, 720));
        setMinimumSize(new java.awt.Dimension(420, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 720));

        jPanel11.setBackground(new java.awt.Color(29, 151, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALERTNUSA");

        jPanel3.setBackground(new java.awt.Color(40, 40, 56));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manajemen Konten");
        jPanel3.add(jLabel2);

        jButton14.setBackground(new java.awt.Color(0, 102, 102));
        jButton14.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("+ Tambah");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jPanel3.add(jButton14);

        pilihanKonten.setBackground(new java.awt.Color(40, 40, 56));
        pilihanKonten.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Katalog");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        pilihanKonten.add(jButton13);

        btnSOS.setBackground(new java.awt.Color(0, 102, 102));
        btnSOS.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnSOS.setForeground(new java.awt.Color(255, 255, 255));
        btnSOS.setText("SOS");
        btnSOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSOSMouseClicked(evt);
            }
        });
        btnSOS.addActionListener(this::btnSOSActionPerformed);
        pilihanKonten.add(btnSOS);

        mainContainerAdmin.setBackground(new java.awt.Color(40, 40, 56));
        mainContainerAdmin.setLayout(new java.awt.CardLayout());

        jScrollPaneKatalog.setBackground(new java.awt.Color(40, 40, 56));

        listKontenKatalog.setBackground(new java.awt.Color(40, 40, 56));

        javax.swing.GroupLayout listKontenKatalogLayout = new javax.swing.GroupLayout(listKontenKatalog);
        listKontenKatalog.setLayout(listKontenKatalogLayout);
        listKontenKatalogLayout.setHorizontalGroup(
            listKontenKatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        listKontenKatalogLayout.setVerticalGroup(
            listKontenKatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        jScrollPaneKatalog.setViewportView(listKontenKatalog);

        mainContainerAdmin.add(jScrollPaneKatalog, "katalogPage");

        jScrollPaneSOS.setBackground(new java.awt.Color(40, 40, 56));

        listKontenSOS.setBackground(new java.awt.Color(40, 40, 56));
        listKontenSOS.setLayout(new javax.swing.BoxLayout(listKontenSOS, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPaneSOS.setViewportView(listKontenSOS);

        mainContainerAdmin.add(jScrollPaneSOS, "SOSPage");

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Kembali");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(this::jButton9ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pilihanKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(mainContainerAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pilihanKonten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainContainerAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSOSActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContainerAdmin.getLayout();
        cl.show(mainContainerAdmin, "katalogPage");

        // 2. PAKSA JALAN METHOD PENARIK DATA DARI DATABASENYA DI SINI, BLI!
        this.loadDataAdmin();
        listKontenKatalog.removeAll();
        listKontenKatalog.setLayout(new javax.swing.BoxLayout(listKontenKatalog, javax.swing.BoxLayout.Y_AXIS));

        // Kueri yang sudah disesuaikan dengan gambar image_e605e4.png
        String query = "SELECT id, disaster_name, description, category, risk_level FROM disasters ORDER BY id ASC";

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query); java.sql.ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("disaster_name"); // Sesuaikan nama kolom
                String deskripsi = rs.getString("description");
                String kategori = rs.getString("category");    // Menangkap enum category
                String levelRisiko = rs.getString("risk_level"); // Menangkap enum risk_level

                // Masukkan variabel yang sesuai ke dalam Constructor kartu abang
                // (Jika kartu abang masih pakai parameter lama, sementara string 'kategori' atau 'levelRisiko' bisa dioper ke posisi parameter ke-4)
                ItemKatalogBencanaAdminPanel kartu = new ItemKatalogBencanaAdminPanel(id, nama, deskripsi, kategori, this);

                listKontenKatalog.add(kartu);
                listKontenKatalog.add(javax.swing.Box.createVerticalStrut(10));
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat katalog: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // 3. Refresh komponen GUI agar kartu langsung dirender keluar secara live
        listKontenKatalog.revalidate();
        listKontenKatalog.repaint();
        jScrollPaneKatalog.revalidate();
        jScrollPaneKatalog.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseClicked

    private void btnSOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSOSMouseClicked
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContainerAdmin.getLayout();
        cl.show(mainContainerAdmin, "SOSPage");

        // 2. Bersihkan dan muat ulang data SOS secara real-time
        listKontenSOS.removeAll();
        listKontenSOS.setLayout(new javax.swing.BoxLayout(listKontenSOS, javax.swing.BoxLayout.Y_AXIS));

        String query = "SELECT id, institution_name, phone_number, region FROM sos_contacts ORDER BY id ASC";
        int jumlahKartu = 0;

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query); java.sql.ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("institution_name");
                String nomor = rs.getString("phone_number");
                String wilayah = rs.getString("region");

                // Buat objek kartu SOS khusus admin (yang ada tombol hapusnya)
                SOSCardAdminPanel kartu = new SOSCardAdminPanel(id, nama, nomor, wilayah, this);
                listKontenSOS.add(kartu);
                listKontenSOS.add(javax.swing.Box.createVerticalStrut(10)); // Jarak antar kartu
                jumlahKartu++;
            }

        } catch (Exception e) {
            System.err.println("[AlertNusa] Gagal memuat data SOS admin: " + e.getMessage());
            e.printStackTrace();
        }

        // Biar kartu tidak melar kaku ke bawah dan scroll-nya aktif sempurna
        listKontenSOS.add(javax.swing.Box.createVerticalGlue());
        jScrollPaneSOS.setViewportView(listKontenSOS);
        jScrollPaneSOS.getVerticalScrollBar().setUnitIncrement(16);

        // Refresh render layar
        listKontenSOS.revalidate();
        listKontenSOS.repaint();
        jScrollPaneSOS.revalidate();
        jScrollPaneSOS.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSOSMouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        java.awt.Component comp = this;
        while (comp != null && !(comp instanceof java.awt.Frame)) {
            comp = comp.getParent();
        }
        java.awt.Frame parentFrame = (java.awt.Frame) comp;

        // 2. CEK HALAMAN AKTIF: Kita cek JScrollPane mana yang sedang terlihat (visible)
        if (jScrollPaneSOS.isVisible()) {

            // JIKA HALAMAN SOS YANG AKTIF: Munculkan dialog tambah kontak SOS
            TambahSOSDialog dialogSOS = new TambahSOSDialog(parentFrame, true, this);
            dialogSOS.setVisible(true);

        } else if (jScrollPaneKatalog.isVisible()) {

            TambahKatalogDialog dialogKatalog = new TambahKatalogDialog(parentFrame, true, this);
            dialogKatalog.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        java.awt.Window ancestor = javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Jika ketemu dan benar itu AdminFrame, langsung suruh panggilLayar menu utama
        if (ancestor instanceof AdminFrame) {
            AdminFrame frameUtama = (AdminFrame) ancestor;

            // Panggil fungsi bawaan abang, arahkan ke nama card menu utama admin (misal: "adminPanel")
            frameUtama.panggilLayar("adminPanel");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSOS;
    public javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPaneKatalog;
    private javax.swing.JScrollPane jScrollPaneSOS;
    private javax.swing.JPanel listKontenKatalog;
    private javax.swing.JPanel listKontenSOS;
    private javax.swing.JPanel mainContainerAdmin;
    private javax.swing.JPanel pilihanKonten;
    // End of variables declaration//GEN-END:variables
public void refreshHalamanSOS() {
        this.btnSOSActionPerformed(null);}

}
