/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.alertnusa.view;
import java.sql.*;
import com.alertnusa.util.DatabaseConnection;
/**
 *
 * @author edy
 */
public class EditBeritaDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditBeritaDialog.class.getName());

    private int id;
    private admBencanaPanel parentPanel;
    /**
     * Creates new form EditKatalogDialog
     */
    public EditBeritaDialog(java.awt.Frame parent, boolean modal, int id, String judul, String tanggal, String isi, admBencanaPanel parentPanel) {
        super(parent != null ? parent : (java.awt.Frame) null, modal);
        initComponents();
        this.id = id;
        this.parentPanel = parentPanel;

        // 1. LANGSUNG SET DATA LAMA KE FORM BIAR ADMIN TINGGAL EDIT, CUY!
        txtTitle.setText(judul);
        txtContent.setText(isi);
        // Catatan: Jika abang punya inputan lokasi di desainer, pasang kueri SELECT lokasi dulu 
        // atau sementara set lokasi kosong/default jika tidak dioper. 
        // Misal dioper: txtLocation.setText(lokasi);

        // Visual gelap estetik runtime
        this.getContentPane().setBackground(new java.awt.Color(30, 30, 36));
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulBencana = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        lblJudulBencana1 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblJudulBencana2 = new javax.swing.JLabel();
        lblJudulBencana3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(40, 40, 56));

        lblJudulBencana.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblJudulBencana.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBencana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBencana.setText("BERITA");

        btnSimpan.setBackground(new java.awt.Color(0, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnBatal.setBackground(new java.awt.Color(0, 102, 102));
        btnBatal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        lblJudulBencana1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblJudulBencana1.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBencana1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBencana1.setText("JUDUL");

        lblJudulBencana2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblJudulBencana2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBencana2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBencana2.setText("LOKASI");

        lblJudulBencana3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblJudulBencana3.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBencana3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBencana3.setText("Konten");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJudulBencana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJudulBencana1)
                                    .addComponent(txtTitle)
                                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                    .addComponent(lblJudulBencana2)
                                    .addComponent(lblJudulBencana3)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulBencana)
                .addGap(36, 36, 36)
                .addComponent(lblJudulBencana1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblJudulBencana2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblJudulBencana3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String judulBaru = txtTitle.getText().trim();
        String isiBaru = txtContent.getText().trim();
        // String lokasiBaru = txtLocation.getText().trim(); // Aktifkan jika ada variabelnya

        if (judulBaru.isEmpty() || isiBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kolom judul dan isi tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Kueri UPDATE data berita berdasarkan ID spesifik
        String query = "UPDATE disaster_news SET title = ?, content = ? WHERE id = ?";

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query)) {

            ps.setString(1, judulBaru);
            ps.setString(2, isiBaru);
            ps.setInt(3, this.id); // Menembak ID berita ini

            int hasil = ps.executeUpdate();
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Berita berhasil diperbarui!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Pemicu Live Refresh layar utama admin secara real-time
                if (parentPanel != null) {
                    parentPanel.loadDataBerita();
                }
                this.dispose(); // Tutup dialog edit
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui berita: " + e.getMessage(), "Error Database", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                EditKatalogDialog dialog = new EditKatalogDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulBencana;
    private javax.swing.JLabel lblJudulBencana1;
    private javax.swing.JLabel lblJudulBencana2;
    private javax.swing.JLabel lblJudulBencana3;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
