/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.alertnusa.view;
import java.sql.*;
import com.alertnusa.util.DatabaseConnection;
/**
 *
 * @author edy
 */
public class EditKatalogDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditKatalogDialog.class.getName());

    private int idBencana;
    private admKontenPanel parentPanel;
    /**
     * Creates new form EditKatalogDialog
     */
    public EditKatalogDialog(java.awt.Frame parent, boolean modal, int id, String nama, String deskripsi, String prep, admKontenPanel parentPanel) {
        super(parent != null ? parent : (java.awt.Frame) null, modal);
        initComponents();
        this.idBencana = id;
        this.parentPanel = parentPanel;

        // Set info komponen dialog
        lblJudulBencana.setText("Edit Konten: " + nama);
        txtEditDeskripsi.setText(deskripsi);
        txtEditPrep.setText(prep);

        // Pengaturan teks area agar otomatis turun baris
        txtEditDeskripsi.setLineWrap(true);
        txtEditDeskripsi.setWrapStyleWord(true);
        txtEditPrep.setLineWrap(true);
        txtEditPrep.setWrapStyleWord(true);

        // Posisikan pop-up otomatis di tengah layar
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulBencana = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditDeskripsi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEditPrep = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(40, 40, 56));

        lblJudulBencana.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblJudulBencana.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBencana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBencana.setText("jLabel1");

        txtEditDeskripsi.setBackground(new java.awt.Color(24, 24, 24));
        txtEditDeskripsi.setColumns(20);
        txtEditDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        txtEditDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtEditDeskripsi);

        txtEditPrep.setBackground(new java.awt.Color(24, 24, 24));
        txtEditPrep.setColumns(20);
        txtEditPrep.setForeground(new java.awt.Color(255, 255, 255));
        txtEditPrep.setRows(5);
        jScrollPane2.setViewportView(txtEditPrep);

        btnSimpan.setBackground(new java.awt.Color(0, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnBatal.setBackground(new java.awt.Color(0, 102, 102));
        btnBatal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudulBencana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulBencana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String deskripsiBaru = txtEditDeskripsi.getText().trim();
        String prepBaru = txtEditPrep.getText().trim();

        // Validasi input kosong
        if (deskripsiBaru.isEmpty() || prepBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Siapkan dua kueri UPDATE untuk masing-masing tabel
        String queryDisaster = "UPDATE disasters SET description = ? WHERE id = ?";
        String queryPrep = "UPDATE preparations SET description = ? WHERE id = ?";
        
        java.sql.Connection conn = null;
        java.sql.PreparedStatement psDisaster = null;
        java.sql.PreparedStatement psPrep = null;

        try {
            conn = com.alertnusa.util.DatabaseConnection.getConnection();

            // Matikan auto-commit demi keamanan (Prinsip Transaksi Database)
            conn.setAutoCommit(false);

            // KUERI 1: Perbarui deskripsi di tabel disasters
            psDisaster = conn.prepareStatement(queryDisaster);
            psDisaster.setString(1, deskripsiBaru);
            psDisaster.setInt(2, idBencana);
            psDisaster.executeUpdate();

            // KUERI 2: Perbarui persiapan di tabel preparations berdasarkan disaster_id
            psPrep = conn.prepareStatement(queryPrep);
            psPrep.setString(1, prepBaru);
            psPrep.setInt(2, idBencana); // idBencana bertindak sebagai disaster_id di tabel preparations
            psPrep.executeUpdate();

            // Jika kedua kueri sukses tanpa eror, commit perubahan ke database
            conn.commit();

            javax.swing.JOptionPane.showMessageDialog(this, "Data Katalog dan Persiapan Bencana berhasil diperbarui!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Pemicu Live Refresh halaman katalog utama admin
            if (parentPanel != null) {
                parentPanel.loadDataAdmin();
            }

            // Tutup pop-up dialog edit
            this.dispose();

        } catch (java.sql.SQLException e) {
            // Jika salah satu kueri gagal, batalkan semua perubahan agar data tidak korup
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (java.sql.SQLException ex) {
                    ex.printStackTrace();
                }
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage(), "Error Database", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            // Tutup semua resource database secara manual
            try {
                if (psDisaster != null) {
                    psDisaster.close();
                }
                if (psPrep != null) {
                    psPrep.close();
                }
                if (conn != null) {
                    conn.setAutoCommit(true);
                    conn.close();
                }
            } catch (java.sql.SQLException e) {
                e.printStackTrace();
            }
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                EditKatalogDialog dialog = new EditKatalogDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJudulBencana;
    private javax.swing.JTextArea txtEditDeskripsi;
    private javax.swing.JTextArea txtEditPrep;
    // End of variables declaration//GEN-END:variables
}
