/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alertnusa.view;

import com.alertnusa.model.userSession;

/**
 *
 * @author edy
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName());

    /**
     * Creates new form Register
     */
    public ForgotPasswordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Confirm_Password = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Confirm_Button = new javax.swing.JButton();
        Confirm_Password_Field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        New_Password_Field = new javax.swing.JPasswordField();
        Password1 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        Username.setText("Email");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Confirm_Password.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        Confirm_Password.setText("Confirm Password");
        jPanel1.add(Confirm_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        Email_Field.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        Email_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Email_Field.addActionListener(this::Email_FieldActionPerformed);
        Email_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Email_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(Email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 260, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Poppins Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Password");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 460, 67));

        Confirm_Button.setBackground(new java.awt.Color(0, 0, 0));
        Confirm_Button.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        Confirm_Button.setForeground(new java.awt.Color(255, 255, 255));
        Confirm_Button.setText("Confirm");
        Confirm_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confirm_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Confirm_ButtonMouseClicked(evt);
            }
        });
        Confirm_Button.addActionListener(this::Confirm_ButtonActionPerformed);
        jPanel1.add(Confirm_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        Confirm_Password_Field.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        Confirm_Password_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Confirm_Password_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Confirm_Password_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(Confirm_Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 260, -1));

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("<html><u>Back To Login...</u></html>");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        New_Password_Field.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        New_Password_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        New_Password_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                New_Password_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(New_Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 260, -1));

        Password1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        Password1.setText("New Password");
        jPanel1.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Username1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        Username1.setText("Username");
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Username_Field.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        Username_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Username_Field.addActionListener(this::Username_FieldActionPerformed);
        Username_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Username_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(Username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_FieldActionPerformed

    private void Email_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Email_FieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            New_Password_Field.requestFocus();
        }
    }//GEN-LAST:event_Email_FieldKeyPressed

    private void Confirm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_ButtonActionPerformed
        
    }//GEN-LAST:event_Confirm_ButtonActionPerformed

    private void Confirm_Password_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Confirm_Password_FieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Confirm_Button.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_Password_FieldKeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LoginFrame formLogin = new LoginFrame();
        formLogin.setLocationRelativeTo(null);
        formLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void New_Password_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_New_Password_FieldKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Confirm_Password_Field.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_New_Password_FieldKeyPressed

    
    private void Confirm_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Confirm_ButtonMouseClicked
        String userIn = Username_Field.getText().trim();
        String emailIn = Email_Field.getText().trim();
        String newPassIn = New_Password_Field.getText();
        String confirmNewPassIn = Confirm_Password_Field.getText();

        
        // 1. Validasi Input Kosong
        if (userIn.isEmpty() || emailIn.isEmpty() || newPassIn.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mohon isi semua kolom!");
            return;
        }

        // 2. Validasi Konfirmasi Password Baru
        if (!newPassIn.equals(confirmNewPassIn)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password baru dan konfirmasi tidak sama!");
            return;
        }

        // 3. Eksekusi Reset Password via UserSession
        if (userSession.resetPassword(userIn, emailIn, newPassIn)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Reset Password Berhasil! Silakan Login kembali.");
            
            clearFields(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal! Username tidak ditemukan atau Email salah.");
        }
    }//GEN-LAST:event_Confirm_ButtonMouseClicked

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Username_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Username_FieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPasswordFrame().setVisible(true));
    }
   

    private void clearFields(){
        Email_Field.setText("");
        Username_Field.setText("");
        New_Password_Field.setText("");
        Confirm_Password_Field.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm_Button;
    private javax.swing.JLabel Confirm_Password;
    private javax.swing.JPasswordField Confirm_Password_Field;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JPasswordField New_Password_Field;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
