/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class ItemBeritaAdminPanel extends javax.swing.JPanel {

    private int id;
    private admBencanaPanel parentPanel;
    /**
     * Creates new form ItemBeritaAdminPanel
     */
    public ItemBeritaAdminPanel(int id, String judul, String tanggal, String isi, admBencanaPanel parentPanel) {
        initComponents();
        this.id = id;
        this.parentPanel = parentPanel;
        
        // Pasang data ke komponen visual di desainer abang
        lblJudulBerita.setText(judul);
        lblTanggal.setText(tanggal);
        txtPratinjau.setText(isi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulBerita = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPratinjau = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 40, 56));

        lblJudulBerita.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblJudulBerita.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBerita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBerita.setText("jLabel1");

        lblTanggal.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTanggal.setText("jLabel1");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtPratinjau.setEditable(false);
        txtPratinjau.setBackground(new java.awt.Color(24, 24, 24));
        txtPratinjau.setColumns(20);
        txtPratinjau.setForeground(new java.awt.Color(255, 255, 255));
        txtPratinjau.setLineWrap(true);
        txtPratinjau.setRows(5);
        txtPratinjau.setToolTipText("");
        txtPratinjau.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPratinjau);

        jPanel1.setBackground(new java.awt.Color(40, 40, 56));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel1.add(btnEdit);

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJudulBerita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulBerita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah kamu yakin ingin menghapus berita ini?",
                "Konfirmasi Hapus",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            // 2. Kueri DELETE menembak ID spesifik berita ini di tabel disaster_news
            String query = "DELETE FROM disaster_news WHERE id = ?";

            try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query)) {

                ps.setInt(1, this.id); // 'this.id' didapat dari constructor kartu saat load data

                int hasil = ps.executeUpdate();
                if (hasil > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Berita berhasil dihapus!",
                            "Sukses",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // 3. Pemicu Live Refresh: Menyuruh panel induk (admBencanaPanel) memuat ulang datanya
                    if (parentPanel != null) {
                        parentPanel.loadDataBerita();
                    }
                }

            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Gagal menghapus berita: " + e.getMessage(),
                        "Error Database",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnHapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulBerita;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTextArea txtPratinjau;
    // End of variables declaration//GEN-END:variables
}
