/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class ItemKatalogBencanaAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemKatalogBencana
     */
    private int idBencana;
    private String namaBencana;
    private String deskripsi;
    private String preparation;
    private admKontenPanel parentPanel;
    
    public ItemKatalogBencanaAdminPanel(int id, String nama, String deskripsi, String preparation, admKontenPanel parent) {
        initComponents();
        this.idBencana = id;
        this.namaBencana = nama;
        this.deskripsi = deskripsi;
        this.preparation = preparation;
        this.parentPanel = parent;

        // Kunci Ukuran Kartu
        java.awt.Dimension ukuranTetap = new java.awt.Dimension(350, 200);
        this.setPreferredSize(ukuranTetap);
        this.setMinimumSize(ukuranTetap);
        this.setMaximumSize(ukuranTetap);

        // Set Teks Komponen
        lblNamaBencana.setText(nama);
        txtDeskripsi.setText(deskripsi);

        // Jinakkan JTextArea
        jScrollPane1.setBorder(null);
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setWrapStyleWord(true);
        txtDeskripsi.setEditable(false); // Sisi list tidak boleh diedit langsung

        // Border hiasan kartu
        this.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 75, 80), 1),
                javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaBencana = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 40, 56));

        lblNamaBencana.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblNamaBencana.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaBencana.setText("jLabel1");

        txtDeskripsi.setBackground(new java.awt.Color(24, 24, 24));
        txtDeskripsi.setColumns(20);
        txtDeskripsi.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        txtDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        txtDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsi);

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(this::btnEditActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNamaBencana)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNamaBencana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        // Instansiasi dan tampilkan pop-up EditKatalogDialog
        EditKatalogDialog dialog = new EditKatalogDialog(
                parentFrame,
                true,
                this.idBencana,
                this.namaBencana,
                this.deskripsi,
                this.preparation,
                this.parentPanel
        );
        dialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNamaBencana;
    private javax.swing.JTextArea txtDeskripsi;
    // End of variables declaration//GEN-END:variables
}
