/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class ListUserAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListUserAdminPanel
     */
    public ListUserAdminPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnUpdatePass = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setMinimumSize(new java.awt.Dimension(380, 90));
        setPreferredSize(new java.awt.Dimension(380, 90));
        setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));
        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 0, 0));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        lblUsername.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("yanto Geming");
        jPanel5.add(lblUsername);

        lblEmail.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("yanto123@gmail.com");
        jPanel5.add(lblEmail);

        lblRole.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setText("Role");
        jPanel5.add(lblRole);

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        jPanel6.setMaximumSize(new java.awt.Dimension(160, 90));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(160, 90));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        btnUpdatePass.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdatePass.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        btnUpdatePass.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePass.setText("Ganti Password");
        btnUpdatePass.addActionListener(this::btnUpdatePassActionPerformed);
        jPanel6.add(btnUpdatePass, new java.awt.GridBagConstraints());

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(btnDelete, gridBagConstraints);

        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnUpdatePass;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblRole;
    public javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
