/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alertnusa.view;

import com.alertnusa.view.ForgotPasswordFrame;
import com.alertnusa.view.DashboardFrame;
import com.alertnusa.model.User;
import com.alertnusa.model.userSession;

/**
 *
 * @author edy
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form Login
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        Login = new javax.swing.JLabel();
        Login_Button = new javax.swing.JButton();
        Register_Hyperlink = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        Password1 = new javax.swing.JLabel();
        ForgotPassword_Hyperlink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        Username.setText("Username");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Username_Field.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        Username_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Username_Field.addActionListener(this::Username_FieldActionPerformed);
        Username_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Username_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(Username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 260, -1));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Poppins Black", 0, 48)); // NOI18N
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("LOGIN");
        Login.setMaximumSize(new java.awt.Dimension(100, 100));
        Login.setMinimumSize(new java.awt.Dimension(100, 100));
        Login.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 290, 67));

        Login_Button.setBackground(new java.awt.Color(0, 0, 0));
        Login_Button.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("LOGIN");
        Login_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseClicked(evt);
            }
        });
        Login_Button.addActionListener(this::Login_ButtonActionPerformed);
        jPanel1.add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        Register_Hyperlink.setFont(new java.awt.Font("Poppins Light", 0, 10)); // NOI18N
        Register_Hyperlink.setForeground(new java.awt.Color(0, 0, 153));
        Register_Hyperlink.setText("<html><u>Register...</u></html>");
        Register_Hyperlink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register_Hyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register_HyperlinkMouseClicked(evt);
            }
        });
        jPanel1.add(Register_Hyperlink, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        Password_Field.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        Password_Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Password_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Password_FieldKeyPressed(evt);
            }
        });
        jPanel1.add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 260, -1));

        Password1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        Password1.setText("Password");
        jPanel1.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        ForgotPassword_Hyperlink.setFont(new java.awt.Font("Poppins Light", 0, 10)); // NOI18N
        ForgotPassword_Hyperlink.setForeground(new java.awt.Color(0, 0, 153));
        ForgotPassword_Hyperlink.setText("<html><u>Forgot Password?</u></html>");
        ForgotPassword_Hyperlink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPassword_Hyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassword_HyperlinkMouseClicked(evt);
            }
        });
        jPanel1.add(ForgotPassword_Hyperlink, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 6, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Username_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Username_FieldKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Password_Field.requestFocus();
        }    
    }//GEN-LAST:event_Username_FieldKeyPressed

    private void Register_HyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_HyperlinkMouseClicked
        RegisterFrame formRegister = new RegisterFrame();
        formRegister.setLocationRelativeTo(null); 
        formRegister.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Register_HyperlinkMouseClicked

    private void Password_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Password_FieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                Login_Button.doClick();
        }
    }//GEN-LAST:event_Password_FieldKeyPressed

    private void ForgotPassword_HyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassword_HyperlinkMouseClicked
        ForgotPasswordFrame formForgotRegister = new ForgotPasswordFrame();
        formForgotRegister.setLocationRelativeTo(null); 
        formForgotRegister.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ForgotPassword_HyperlinkMouseClicked

    private void Login_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseClicked
        String userIn = Username_Field.getText().trim();
        String passIn = Password_Field.getText();

        // 1. Gunakan UserSession untuk verifikasi (Logika Terpusat)
        if (userSession.login(userIn, passIn)) {
            // 2. Ambil data user yang berhasil login
            User userAktif = userSession.getCurrentUser();


            // Menampilkan pesan di GUI menggunakan email (via Getter)
            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil! \nHai " + userAktif.getRoleName());
            DashboardFrame formDashboard = new DashboardFrame();
            formDashboard.setLocationRelativeTo(null);
            formDashboard.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Username atau Password salah!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Login_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgotPassword_Hyperlink;
    private javax.swing.JLabel Login;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Password1;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Register_Hyperlink;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
