/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view; 
/**
 *
 * @author edy
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public LoginPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        alertLabel = new javax.swing.JLabel();
        welcomeLabel2 = new javax.swing.JLabel();
        User_Field = new javax.swing.JTextField();
        welcomeLabel3 = new javax.swing.JLabel();
        RememberMe_CheckBox = new javax.swing.JCheckBox();
        welcomeLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        welcomeLabel5 = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        welcomeLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(420, 720));
        setMinimumSize(new java.awt.Dimension(420, 720));
        setPreferredSize(new java.awt.Dimension(420, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 720));

        jPanel11.setBackground(new java.awt.Color(29, 151, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALERTNUSA");

        jPanel1.setBackground(new java.awt.Color(40, 40, 56));

        welcomeLabel.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("LOGIN");

        alertLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        alertLabel.setForeground(new java.awt.Color(255, 0, 0));
        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        welcomeLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel2.setText("Username/Email");

        User_Field.setText("admin");

        welcomeLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel3.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel3.setText("Password");

        RememberMe_CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        RememberMe_CheckBox.setText("Remember Me");

        welcomeLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel4.setForeground(new java.awt.Color(153, 153, 255));
        welcomeLabel4.setText("<html><p style=\"text-decoration: underline;\">Forgot Password</p></html?>");
        welcomeLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomeLabel4MouseClicked(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("LOGIN");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(this::jButton9ActionPerformed);

        welcomeLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel5.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel5.setText("<html>Don't Have an Account? <span style=\"text-decoration: underline;\">Sign Up</span></html>");
        welcomeLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        welcomeLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomeLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                welcomeLabel5MouseEntered(evt);
            }
        });

        Password_Field.setText("adminanjing");

        welcomeLabel6.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        welcomeLabel6.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel6.setText("Enter your credentials here!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addComponent(alertLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(welcomeLabel2)
                                    .addComponent(welcomeLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RememberMe_CheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(welcomeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(User_Field, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Password_Field, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(welcomeLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jButton9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(38, 38, 38)
                .addComponent(welcomeLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(User_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(welcomeLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RememberMe_CheckBox)
                    .addComponent(welcomeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        
        String identifier = User_Field.getText().trim();
        String password = new String(Password_Field.getPassword()).trim();

        if (identifier.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username/Email dan Password tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean isLoginSuccess = com.alertnusa.model.userSession.login(identifier, password);

        if (isLoginSuccess) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selamat Datang, " + com.alertnusa.model.userSession.getCurrentUser().getUsername() + "!", "Login Berhasil", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            java.awt.Window ancestor = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (ancestor instanceof javax.swing.JFrame) {
                ancestor.dispose();
            }
            
            String roleUser = com.alertnusa.model.userSession.getCurrentUser().getRole();

            if (roleUser != null && roleUser.equalsIgnoreCase("admin")) {
                // Jika admin, buka AdminFrame
                new AdminFrame().setVisible(true);
            } else {
                // Jika member atau selain admin, buka MainFrame
                new MainFrame().setVisible(true);
            }
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Username/Email atau Password salah!", "Login Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void welcomeLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeLabel5MouseClicked
        java.awt.Container parent = this.getParent(); 

            // Memastikan induknya memakai CardLayout, lalu pindah layar
            if (parent != null && parent.getLayout() instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) parent.getLayout();
                // PENTING: Ganti "login_screen" dengan Card Name panel login milikmu
                cl.show(parent, "register_screen"); 
            }    // TODO add your handling code here:
    }//GEN-LAST:event_welcomeLabel5MouseClicked

    private void welcomeLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeLabel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_welcomeLabel5MouseEntered

    private void welcomeLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeLabel4MouseClicked
            java.awt.Container parent = this.getParent(); 

            if (parent != null && parent.getLayout() instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) parent.getLayout();
                cl.show(parent, "fgpassword_screen"); 
            }    // TODO add your handling code here:
    }//GEN-LAST:event_welcomeLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JCheckBox RememberMe_CheckBox;
    private javax.swing.JTextField User_Field;
    private javax.swing.JLabel alertLabel;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel2;
    private javax.swing.JLabel welcomeLabel3;
    private javax.swing.JLabel welcomeLabel4;
    private javax.swing.JLabel welcomeLabel5;
    private javax.swing.JLabel welcomeLabel6;
    // End of variables declaration//GEN-END:variables
}
