/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        int loggedInUserId = com.alertnusa.model.userSession.isLoggedIn() 
                             ? com.alertnusa.model.userSession.getCurrentUser().getId() 
                             : 0; 
        
        PreparationPanel prepPanel = new PreparationPanel();

        mainPanel.add(new DashboardPanel(), "dashboard_screen");
        mainPanel.add(prepPanel, "preparation_screen"); // <-- Menggunakan objek yang sama!
        mainPanel.add(new EvacuationPanel(), "evacuation_screen"); // sesuaikan penamaan lamamu
        mainPanel.add(new SOSPanel(), "sos_screen");
        mainPanel.add(new LoginPanel(), "login_screen");
        mainPanel.add(new RegisterPanel(), "register_screen");
        mainPanel.add(new ForgotPasswordPanel(), "fgpassword_screen");

        // 4. Perintahkan controller untuk memuat data berdasarkan user yang sedang aktif
        if (prepPanel.getPrepController() != null) {
            prepPanel.getPrepController().loadPreparationData(loggedInUserId);
        }

        // Tampilkan halaman utama dashboard terlebih dahulu
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "dashboard_screen");

        mainPanel.revalidate();
        mainPanel.repaint();
        
    }
    public void panggilCard(String namaCardTujuan) {
        if (mainPanel != null && mainPanel.getLayout() instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
            cl.show(mainPanel, namaCardTujuan);
        } else {
            System.err.println("[AlertNusa Error] mainPanel tidak menggunakan CardLayout atau bernilai null!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JPanel();
        homeV = new javax.swing.JLabel();
        homeV1 = new javax.swing.JLabel();
        homeV2 = new javax.swing.JLabel();
        homeV3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        dashboardPanel1 = new com.alertnusa.view.DashboardPanel();
        evacuationPanel1 = new com.alertnusa.view.EvacuationPanel();
        preparationPanel1 = new com.alertnusa.view.PreparationPanel();
        sOSPanel1 = new com.alertnusa.view.SOSPanel();
        loginPanel1 = new com.alertnusa.view.LoginPanel();
        registerPanel1 = new com.alertnusa.view.RegisterPanel();
        forgotPasswordPanel1 = new com.alertnusa.view.ForgotPasswordPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 720));

        bar.setBackground(new java.awt.Color(40, 40, 56));
        bar.setMaximumSize(new java.awt.Dimension(408, 60));
        bar.setMinimumSize(new java.awt.Dimension(408, 60));

        homeV.setBackground(new java.awt.Color(0, 0, 0));
        homeV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/homeIcon.png"))); // NOI18N
        homeV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeVMouseClicked(evt);
            }
        });

        homeV1.setBackground(new java.awt.Color(0, 0, 0));
        homeV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/preparationIcon.png"))); // NOI18N
        homeV1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeV1MouseClicked(evt);
            }
        });

        homeV2.setBackground(new java.awt.Color(0, 0, 0));
        homeV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/evacuationIcon.png"))); // NOI18N
        homeV2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeV2MouseClicked(evt);
            }
        });

        homeV3.setBackground(new java.awt.Color(0, 0, 0));
        homeV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/emergencyIcon.png"))); // NOI18N
        homeV3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeV3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeV)
                .addGap(80, 80, 80)
                .addComponent(homeV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(homeV2)
                .addGap(73, 73, 73)
                .addComponent(homeV3)
                .addGap(16, 16, 16))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeV3)
                    .addComponent(homeV2)
                    .addComponent(homeV1)
                    .addComponent(homeV))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(bar, java.awt.BorderLayout.SOUTH);

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(dashboardPanel1, "dashboard_screen");
        mainPanel.add(evacuationPanel1, "evacuation_screen");
        mainPanel.add(preparationPanel1, "preparation_screen");
        mainPanel.add(sOSPanel1, "sos_screen");
        mainPanel.add(loginPanel1, "login_screen");
        mainPanel.add(registerPanel1, "register_screen");
        mainPanel.add(forgotPasswordPanel1, "fgpassword_screen");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeV1MouseClicked
        int loggedInUserId = com.alertnusa.model.userSession.isLoggedIn() 
                            ? com.alertnusa.model.userSession.getCurrentUser().getId() 
                            : 0; 

       // Cari panel yang sudah tertanam di CardLayout tanpa menumpuknya dari awal
       for (java.awt.Component comp : mainPanel.getComponents()) {
           if (comp instanceof PreparationPanel) {
               PreparationPanel prepPanel = (PreparationPanel) comp;
               if (prepPanel.getPrepController() != null) {
                   // Paksa sedot data teranyar milik user aktif dari database
                   prepPanel.getPrepController().loadPreparationData(loggedInUserId);
               }
               break;
           }
       }

       java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
       cl.show(mainPanel, "preparation_screen");
        
        // 4. Render ulang container utama
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_homeV1MouseClicked

    private void homeV2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeV2MouseClicked
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "evacuation_screen");    // TODO add your handling code here:
    }//GEN-LAST:event_homeV2MouseClicked

    private void homeV3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeV3MouseClicked
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "sos_screen");
    }//GEN-LAST:event_homeV3MouseClicked

    private void homeVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeVMouseClicked
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "dashboard_screen");    // TODO add your handling code here:
    }//GEN-LAST:event_homeVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    public void panggilLayar(String namaCard) {
        // GANTI 'mainPanel' dengan nama variabel JPanel pembungkus CardLayout milikmu yang dicatat di Langkah 1 tadi!
        if (mainPanel.getLayout() instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
            cl.show(mainPanel, namaCard);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private com.alertnusa.view.DashboardPanel dashboardPanel1;
    private com.alertnusa.view.EvacuationPanel evacuationPanel1;
    private com.alertnusa.view.ForgotPasswordPanel forgotPasswordPanel1;
    private javax.swing.JLabel homeV;
    private javax.swing.JLabel homeV1;
    private javax.swing.JLabel homeV2;
    private javax.swing.JLabel homeV3;
    private com.alertnusa.view.LoginPanel loginPanel1;
    private javax.swing.JPanel mainPanel;
    private com.alertnusa.view.PreparationPanel preparationPanel1;
    private com.alertnusa.view.RegisterPanel registerPanel1;
    private com.alertnusa.view.SOSPanel sOSPanel1;
    // End of variables declaration//GEN-END:variables
}
