/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class NewsCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewsCardPanel
     */
    public NewsCardPanel(String judul, String konten, String lokasi, String tanggal) {
        initComponents();
        java.awt.Dimension ukuranDesainer = new java.awt.Dimension(350, 200);
        this.setPreferredSize(ukuranDesainer);
        this.setMinimumSize(ukuranDesainer);
        this.setMaximumSize(ukuranDesainer);

        // 1. Eksekusi bind data ke nama variabel asli abang
        lblJudulBerita.setText(judul);
        lblInfo.setText(lokasi + " | " + tanggal);
        txtKonten.setText(konten);

        // 2. JINAKKAN SCROLLBAR: Matikan border kaku & paksa background menyatu
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.getViewport().setBackground(txtKonten.getBackground());

        // (Opsional) Memastikan text area membungkus baris otomatis dengan rapi
        txtKonten.setLineWrap(true);
        txtKonten.setWrapStyleWord(true);
        
        javax.swing.border.Border garisTepi = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 75, 80), 1);
        javax.swing.border.Border paddingDalam = javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10);

// Gabungkan kedua border dan pasang ke kartu
        this.setBorder(javax.swing.BorderFactory.createCompoundBorder(garisTepi, paddingDalam));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulBerita = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKonten = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(40, 40, 56));

        lblJudulBerita.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblJudulBerita.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulBerita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulBerita.setText("jLabel1");

        lblInfo.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("jLabel1");

        jScrollPane1.setBackground(new java.awt.Color(24, 24, 24));

        txtKonten.setBackground(new java.awt.Color(24, 24, 24));
        txtKonten.setColumns(20);
        txtKonten.setForeground(new java.awt.Color(255, 255, 255));
        txtKonten.setRows(5);
        txtKonten.setOpaque(false);
        jScrollPane1.setViewportView(txtKonten);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJudulBerita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblJudulBerita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblJudulBerita;
    private javax.swing.JTextArea txtKonten;
    // End of variables declaration//GEN-END:variables
}
