/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class PreparationPanel extends javax.swing.JPanel {
    private com.alertnusa.controller.PreparationController prepController;
    /**
     * Creates new form PreparationPanel
     */
    public PreparationPanel() {
        initComponents();
        jPanel3.removeAll();
        this.prepController = new com.alertnusa.controller.PreparationController(this);
        
        try {
            this.prepController.loadPreparationData(1);
        } catch (Exception e) {
            System.err.println("Error pemicuan mandiri panel: " + e.getMessage());
        }
    }
    
    public com.alertnusa.controller.PreparationController getPrepController() {
        return this.prepController;
    }
    
    public void initPreparationChecklist(java.util.List<com.alertnusa.model.PreparationItem> itemList, java.util.List<Integer> checkedIds) {
        jPanel3.removeAll();
        
        for (com.alertnusa.model.PreparationItem item : itemList) {
            javax.swing.JCheckBox checkBox = new javax.swing.JCheckBox(item.getTitle());
            
            checkBox.setForeground(new java.awt.Color(255, 255, 255));
            checkBox.setFont(new java.awt.Font("Poppins", 0, 14)); 
            checkBox.setOpaque(false);
            
            // Simpan ID asli item database ke komponen JCheckBox
            checkBox.putClientProperty("preparationId", item.getId());
            
            // ============================================================
            // KUNCI UTAMA: Cek apakah ID item ini ada di dalam list checkedIds MySQL
            // ============================================================
            System.out.println("Memeriksa Item ID: " + item.getId() + " | List Centang dari DB: " + checkedIds);
            
            if (checkedIds != null && checkedIds.contains(item.getId())) {
                checkBox.setSelected(true); 
                System.out.println("-> BERHASIL DICENTANG: " + item.getTitle()); // Taruh ini juga
            }
            // ============================================================
            
            checkBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
            jPanel3.add(checkBox);
        }
        jPanel3.revalidate();
        jPanel3.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(420, 720));
        setMinimumSize(new java.awt.Dimension(420, 720));
        setPreferredSize(new java.awt.Dimension(420, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 720));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Simpan Perubahan");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALERTNUSA");

        jPanel11.setBackground(new java.awt.Color(29, 151, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("List Kesiapan");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel3.setBackground(new java.awt.Color(40, 40, 56));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel3);
        jPanel3.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 261, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if (!com.alertnusa.model.userSession.isLoggedIn()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Anda masuk sebagai Guest. Silakan login terlebih dahulu untuk menyimpan perubahan!", 
                "Akses Ditolak", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Menghentikan proses eksekusi, tidak terjadi apa-apa di database
        }

        // 2. Jika lolos, berarti user terautentikasi (Admin / Member seperti Edy)
        int loggedInUserId = com.alertnusa.model.userSession.getCurrentUser().getId();

        java.util.List<Integer> checkedIds = new java.util.ArrayList<>();

        // 3. Ambil semua id checkbox yang sedang dicentang
        for (java.awt.Component comp : jPanel3.getComponents()) {
            if (comp instanceof javax.swing.JCheckBox) {
                javax.swing.JCheckBox cb = (javax.swing.JCheckBox) comp;
                if (cb.isSelected()) {
                    int prepId = (int) cb.getClientProperty("preparationId");
                    checkedIds.add(prepId);
                }
            }
        }

        // 4. Eksekusi simpan permanen ke MySQL via Controller
        if (this.prepController != null) {
            this.prepController.saveChecklist(loggedInUserId, checkedIds);

            // Cetak log dinamis ke konsol NetBeans untuk debugging
            System.out.println("Berhasil memperbarui data checklist untuk User ID: " + loggedInUserId);

            // Sinkronisasi ulang data terbaru dari database ke UI
            this.prepController.loadPreparationData(loggedInUserId);

            javax.swing.JOptionPane.showMessageDialog(this, "Perubahan checklist berhasil disimpan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
