/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class PreparationPanel extends javax.swing.JPanel {
    private com.alertnusa.controller.PreparationController prepController;
    /**
     * Creates new form PreparationPanel
     */
    public PreparationPanel() {
        initComponents();
        
        initDropdownBencana(); 
        loadChecklistBencana();
        this.prepController = new com.alertnusa.controller.PreparationController(this);
        
    }
    
    public void initDropdownBencana() {
        cmbBencana.removeAllItems();
        String query = "SELECT disaster_name FROM disasters ORDER BY id ASC";

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query); java.sql.ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                cmbBencana.addItem(rs.getString("disaster_name"));
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat dropdown bencana: " + e.getMessage());
        }
    }
    
    public void loadChecklistBencana() {
        panelChecklist.removeAll();
        jScrollPane1.setViewportView(panelChecklist); // Memastikan scroll pane mendeteksi panel yang kosong bersih

        String bencanaTerpilih = (cmbBencana.getSelectedItem() != null) ? cmbBencana.getSelectedItem().toString() : "";
        
        if (bencanaTerpilih.isEmpty() && cmbBencana.getItemCount() > 0) {
            bencanaTerpilih = cmbBencana.getItemAt(0).toString();
            cmbBencana.setSelectedIndex(0); // Setel agar visual dropdown-nya ikut terpilih
        }
        
        if (bencanaTerpilih.isEmpty()) {
            panelChecklist.revalidate();
            panelChecklist.repaint();
            return;
        }

        int idUserAktif = 0;
        if (com.alertnusa.model.userSession.getCurrentUser() != null) {
            idUserAktif = com.alertnusa.model.userSession.getCurrentUser().getId();
        }

        String query = "SELECT p.id, p.title, p.description, "
                + "(SELECT COUNT(*) FROM user_preparations up WHERE up.preparation_id = p.id AND up.user_id = ?) as sudah_centang "
                + "FROM preparations p "
                + "INNER JOIN disasters d ON p.disaster_id = d.id "
                + "WHERE d.disaster_name = ?";

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query)) {

            ps.setInt(1, idUserAktif);
            ps.setString(2, bencanaTerpilih);

            try (java.sql.ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    int idPrep = rs.getInt("id");
                    String judul = rs.getString("title");
                    String deskripsi = rs.getString("description");
                    boolean isChecked = rs.getInt("sudah_centang") > 0;

                    String formatTeksHTML = "<html><font color='white'><b>" + judul + "</b><br>" + deskripsi.replace("\n", "<br>") + "</font></html>";

                    javax.swing.JCheckBox chk = new javax.swing.JCheckBox(formatTeksHTML);
                    chk.setSelected(isChecked);
                    chk.setOpaque(false);
                    chk.setName(String.valueOf(idPrep));
                    chk.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 15, 5));

                    // Tambahkan checkbox dinamis ke dalam panel
                    panelChecklist.add(chk);
                }
            }
        } catch (Exception e) {
            System.err.println("Error load checklist: " + e.getMessage());
            e.printStackTrace();
        }

        // 2. FIX SAKTI: Segarkan kembali struktur JScrollPane agar layout box-nya menghitung ulang komponen baru
        panelChecklist.revalidate();
        panelChecklist.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }
    
    public com.alertnusa.controller.PreparationController getPrepController() {
        return this.prepController;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelChecklist = new javax.swing.JPanel();
        cmbBencana = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(420, 720));
        setMinimumSize(new java.awt.Dimension(420, 720));
        setPreferredSize(new java.awt.Dimension(420, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 720));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Simpan Perubahan");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALERTNUSA");

        jPanel11.setBackground(new java.awt.Color(29, 151, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("List Kesiapan");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        panelChecklist.setBackground(new java.awt.Color(40, 40, 56));
        panelChecklist.setLayout(new javax.swing.BoxLayout(panelChecklist, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelChecklist);
        panelChecklist.getAccessibleContext().setAccessibleDescription("");

        cmbBencana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBencana.setMaximumSize(new java.awt.Dimension(200, 30));
        cmbBencana.setMinimumSize(new java.awt.Dimension(200, 30));
        cmbBencana.setPreferredSize(new java.awt.Dimension(200, 30));
        cmbBencana.addActionListener(this::cmbBencanaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 261, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbBencana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(cmbBencana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if (!com.alertnusa.model.userSession.isLoggedIn()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan login terlebih dahulu!", "Akses Ditolak", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String bencanaTerpilih = (cmbBencana.getSelectedItem() != null) ? cmbBencana.getSelectedItem().toString() : "";
        if (bencanaTerpilih.isEmpty()) {
            return;
        }

        int loggedInUserId = com.alertnusa.model.userSession.getCurrentUser().getId();
        java.util.List<Integer> checkedIds = new java.util.ArrayList<>();

        // 1. Ambil semua ID checkbox yang sedang dicentang di panel aktif saat ini
        for (java.awt.Component comp : panelChecklist.getComponents()) {
            if (comp instanceof javax.swing.JCheckBox) {
                javax.swing.JCheckBox cb = (javax.swing.JCheckBox) comp;
                if (cb.isSelected() && cb.getName() != null) {
                    checkedIds.add(Integer.parseInt(cb.getName()));
                }
            }
        }

        // =========================================================================
        // SOLUSI UTAMA: Hapus centang LAMA HANYA untuk bencana yang sedang dipilih!
        // =========================================================================
        String sqlDeleteSpesifik
                = "DELETE up FROM user_preparations up "
                + "INNER JOIN preparations p ON up.preparation_id = p.id "
                + "INNER JOIN disasters d ON p.disaster_id = d.id "
                + "WHERE up.user_id = ? AND d.disaster_name = ?";

        String sqlInsertNew = "INSERT INTO user_preparations (user_id, preparation_id) VALUES (?, ?)";

        try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection()) {
            conn.setAutoCommit(false); // Mode transaksi aman baku

            // Step A: Bersihkan riwayat lama KHUSUS bencana terpilih ini saja
            try (java.sql.PreparedStatement psDel = conn.prepareStatement(sqlDeleteSpesifik)) {
                psDel.setInt(1, loggedInUserId);
                psDel.setString(2, bencanaTerpilih);
                psDel.executeUpdate();
            }

            // Step B: Masukkan data centang yang baru di-checklist oleh user
            if (!checkedIds.isEmpty()) {
                try (java.sql.PreparedStatement psIns = conn.prepareStatement(sqlInsertNew)) {
                    for (int idPrep : checkedIds) {
                        psIns.setInt(1, loggedInUserId);
                        psIns.setInt(2, idPrep);
                        psIns.addBatch();
                    }
                    psIns.executeBatch();
                }
            }

            conn.commit(); // Simpan permanen perubahan ke database
            System.out.println("[AlertNusa] Sukses update checklist bencana: " + bencanaTerpilih);

            // Segarkan UI biar data centang ter-load sempurna
            loadChecklistBencana();

            javax.swing.JOptionPane.showMessageDialog(this, "Perubahan berhasil disimpan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void cmbBencanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBencanaActionPerformed
        loadChecklistBencana();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBencanaActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBencana;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelChecklist;
    // End of variables declaration//GEN-END:variables
}
