/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

import com.alertnusa.model.userSession;
import com.alertnusa.util.passwordValidator;

/**
 *
 * @author edy
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public RegisterPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        welcomeLabel1 = new javax.swing.JLabel();
        welcomeLabel2 = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        welcomeLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        welcomeLabel5 = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        welcomeLabel6 = new javax.swing.JLabel();
        Confirm_Password_Field = new javax.swing.JPasswordField();
        Email_Field = new javax.swing.JTextField();
        welcomeLabel7 = new javax.swing.JLabel();
        alertLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(420, 720));
        setMinimumSize(new java.awt.Dimension(420, 720));
        setPreferredSize(new java.awt.Dimension(420, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 720));

        jPanel11.setBackground(new java.awt.Color(29, 151, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALERTNUSA");

        jPanel1.setBackground(new java.awt.Color(40, 40, 56));

        welcomeLabel.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("REGISTER");

        welcomeLabel1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        welcomeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel1.setText("Enter your credentials here!");

        welcomeLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel2.setText("Username");

        Username_Field.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N

        welcomeLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel3.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel3.setText("Password");

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("REGISTER");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(this::jButton9ActionPerformed);

        welcomeLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel5.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel5.setText("<html>Already Have an Account? <span style=\"text-decoration: underline;\">Sign In</span></html>");
        welcomeLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomeLabel5MouseClicked(evt);
            }
        });

        welcomeLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel6.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel6.setText("Confirm Password");

        Email_Field.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N

        welcomeLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        welcomeLabel7.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel7.setText("Email");

        alertLabel.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        alertLabel.setForeground(new java.awt.Color(255, 0, 0));
        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Confirm_Password_Field))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(welcomeLabel1)
                                .addComponent(welcomeLabel2)
                                .addComponent(welcomeLabel3)
                                .addComponent(Password_Field)
                                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(welcomeLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(welcomeLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton9)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(alertLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel1)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(welcomeLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirm_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        String emailIn = Email_Field.getText().trim();
        String userIn = Username_Field.getText().trim();
        String passIn = Password_Field.getText();
        String confirmPassIn = Confirm_Password_Field.getText(); 

        // 2. Validasi Input Kosong
        if (emailIn.isEmpty() || userIn.isEmpty() || passIn.isEmpty()) {
            alertLabel.setText("Mohon isi semua kolom!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
            return;
        }

        // 3. Validasi Password
        if (!passIn.equals(confirmPassIn)) {
            alertLabel.setText("Konfirmasi password salah!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
            return;
        }
        if (passIn.length() < 8) {
            alertLabel.setText("Password minimal 8 karakter!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
            return;
        }

        // 2. Cek Angka (Rekursif)
        if (!passwordValidator.checker(passIn, 0, 1)) {
            alertLabel.setText("Password harus mengandung minimal satu angka!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
            return;
        }

        // 3. Cek Huruf Besar (Rekursif)
        if (!passwordValidator.checker(passIn, 0, 2)) {
            alertLabel.setText("Password harus mengandung minimal satu huruf kapital!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
            return;
        }

        // 4. Cek Simbol (Rekursif)
        if (!passwordValidator.checker(passIn, 0, 3)) {
            alertLabel.setText("Password harus mengandung minimal satu simbol (!@#$ dll)!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
            return;
        }

        // 4. Gunakan Method Overloading & Encapsulation
        // Kita cek dulu apakah username tersedia menggunakan HashMap yang ada di UserSession
        if (userSession.isUsernameTaken(userIn)) {
            alertLabel.setText("Username sudah dipakai!");
            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> alertLabel.setText(""));
            timer.setRepeats(false);
            timer.start();
        } else {
            // Memanggil Method Overload: addUser(email, user, pass)
            userSession.addUser(emailIn, userIn, passIn);

            javax.swing.JOptionPane.showMessageDialog(this, "Register Sukses!");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void welcomeLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeLabel5MouseClicked
        java.awt.Container parent = this.getParent(); 

            // Memastikan induknya memakai CardLayout, lalu pindah layar
            if (parent != null && parent.getLayout() instanceof java.awt.CardLayout) {
                java.awt.CardLayout cl = (java.awt.CardLayout) parent.getLayout();
                // PENTING: Ganti "login_screen" dengan Card Name panel login milikmu
                cl.show(parent, "login_screen"); 
            }    // TODO add your handling code here:
    }//GEN-LAST:event_welcomeLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirm_Password_Field;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel alertLabel;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel1;
    private javax.swing.JLabel welcomeLabel2;
    private javax.swing.JLabel welcomeLabel3;
    private javax.swing.JLabel welcomeLabel5;
    private javax.swing.JLabel welcomeLabel6;
    private javax.swing.JLabel welcomeLabel7;
    // End of variables declaration//GEN-END:variables
}
