/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class SOSCardPanel extends javax.swing.JPanel {

    private String nomorTelepon;
    
    public SOSCardPanel(String nama, String nomor, String wilayah, String deskripsi) {
        initComponents();
        this.nomorTelepon = nomor;

        // =========================================================================
        // SINKRONISASI UKURAN BARU: 350 x 205 piksel
        // =========================================================================
        java.awt.Dimension ukuranTetap = new java.awt.Dimension(350, 205);
        this.setPreferredSize(ukuranTetap);
        this.setMinimumSize(ukuranTetap);
        this.setMaximumSize(ukuranTetap);

        lblNamaInstansi.setText(nama);
        lblRegion.setText("[" + wilayah + "]");
        lblNomor.setText(nomor);
        txtDeskripsi.setText(deskripsi);

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.getViewport().setBackground(txtDeskripsi.getBackground());
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setWrapStyleWord(true);

        javax.swing.border.Border garisTepi = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 75, 80), 1);
        javax.swing.border.Border paddingDalam = javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10);
        this.setBorder(javax.swing.BorderFactory.createCompoundBorder(garisTepi, paddingDalam));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaInstansi = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        lblNomor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        btnHubungi = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 40, 56));

        lblNamaInstansi.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblNamaInstansi.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaInstansi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaInstansi.setText("jLabel1");

        lblRegion.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblRegion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegion.setText("jLabel1");

        lblNomor.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblNomor.setForeground(new java.awt.Color(255, 255, 255));
        lblNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomor.setText("jLabel1");

        txtDeskripsi.setEditable(false);
        txtDeskripsi.setBackground(new java.awt.Color(24, 24, 24));
        txtDeskripsi.setColumns(20);
        txtDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        txtDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsi);

        btnHubungi.setBackground(new java.awt.Color(0, 102, 102));
        btnHubungi.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnHubungi.setForeground(new java.awt.Color(255, 255, 255));
        btnHubungi.setText("Hubungi");
        btnHubungi.addActionListener(this::btnHubungiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHubungi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(lblNamaInstansi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNamaInstansi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHubungi)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHubungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubungiActionPerformed
        try {
            // Bersihkan nomor dari spasi atau strip jika ada
            String cleanNumber = nomorTelepon.replaceAll("[^0-9]", "");

            // Format WhatsApp Indonesia (jika diawali 08, ganti ke 628)
            if (cleanNumber.startsWith("0")) {
                cleanNumber = "62" + cleanNumber.substring(1);
            }

            // Buka Browser otomatis mengarah ke WA instansi darurat
            String url = "https://wa.me/" + cleanNumber;
            java.awt.Desktop.getDesktop().browse(new java.net.URI(url));

        } catch (Exception e) {
            // Jika nomor pendek (seperti 112 / 118 / 123), buat alert simulasi telepon biasa
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Melakukan panggilan darurat ke: " + nomorTelepon,
                    "Dialing SOS",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHubungiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHubungi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNamaInstansi;
    private javax.swing.JLabel lblNomor;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JTextArea txtDeskripsi;
    // End of variables declaration//GEN-END:variables
}