/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alertnusa.view;

/**
 *
 * @author edy
 */
public class SOSCardAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form SOSCardAdminPanel
     */
    private int idSOS;
    private admKontenPanel parentPanel;
    
    public SOSCardAdminPanel(int id, String nama, String nomor, String wilayah, admKontenPanel parent) {
        initComponents();
        this.idSOS = id;
        this.parentPanel = parent;

        // 1. KUNCI DIMENSI KARTU SECARA ABSOLUT (350 x 205)
        java.awt.Dimension ukuranTetap = new java.awt.Dimension(350, 205);
        this.setPreferredSize(ukuranTetap);
        this.setMinimumSize(ukuranTetap);
        this.setMaximumSize(ukuranTetap);

        // 2. Set Teks Komponen
        lblNamaInstansi.setText(nama);
        lblRegion.setText("[" + wilayah + "]");
        lblNomor.setText(nomor);

        // 3. Beri Border Kalem + Padding Dalam Kartu
        javax.swing.border.Border garisTepi = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 75, 80), 1);
        javax.swing.border.Border paddingDalam = javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12);
        this.setBorder(javax.swing.BorderFactory.createCompoundBorder(garisTepi, paddingDalam));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegion = new javax.swing.JLabel();
        lblNamaInstansi = new javax.swing.JLabel();
        lblNomor = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 40, 56));

        lblRegion.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblRegion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegion.setText("jLabel1");

        lblNamaInstansi.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblNamaInstansi.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaInstansi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaInstansi.setText("jLabel1");

        lblNomor.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblNomor.setForeground(new java.awt.Color(255, 255, 255));
        lblNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomor.setText("jLabel1");

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaInstansi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(btnHapus)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNamaInstansi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnHapus)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus instansi " + lblNamaInstansi.getText() + "?",
                "Konfirmasi Hapus SOS",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        // 2. Jika Admin klik 'YES'
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            String query = "DELETE FROM sos_contacts WHERE id = ?";

            try (java.sql.Connection conn = com.alertnusa.util.DatabaseConnection.getConnection(); java.sql.PreparedStatement ps = conn.prepareStatement(query)) {

                ps.setInt(1, this.idSOS);
                int rows = ps.executeUpdate();

                if (rows > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Kontak darurat berhasil dihapus!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // 3. Refresh otomatis halaman SOS admin dengan memicu ulang fungsi load-nya
                    if (parentPanel != null) {
                        parentPanel.refreshHalamanSOS();
                    }
                }
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel lblNamaInstansi;
    private javax.swing.JLabel lblNomor;
    private javax.swing.JLabel lblRegion;
    // End of variables declaration//GEN-END:variables
}
