/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alertnusa.view;
import com.alertnusa.model.Bencana;
import com.alertnusa.model.BencanaRepository;
import java.util.List;

/**
 *
 * @author edy
 */
public class SOSFrameX extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SOSFrameX.class.getName());

    /**
     * Creates new form DashboardFrameX
     */
    public SOSFrameX() {
        initComponents();

        this.setSize(425, 750);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homeV = new javax.swing.JLabel();
        homeV1 = new javax.swing.JLabel();
        homeV2 = new javax.swing.JLabel();
        homeV3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTema1 = new javax.swing.JPanel();
        labelJudul1 = new javax.swing.JLabel();
        labelDeskripsi1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 40, 56));
        jPanel1.setMaximumSize(new java.awt.Dimension(408, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(408, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(408, 60));

        homeV.setBackground(new java.awt.Color(0, 0, 0));
        homeV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/homeIcon.png"))); // NOI18N
        homeV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeVMouseClicked(evt);
            }
        });

        homeV1.setBackground(new java.awt.Color(0, 0, 0));
        homeV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/preparationIcon.png"))); // NOI18N
        homeV1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeV1MouseClicked(evt);
            }
        });

        homeV2.setBackground(new java.awt.Color(0, 0, 0));
        homeV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/evacuationIcon.png"))); // NOI18N
        homeV2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeV2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeV2MouseClicked(evt);
            }
        });

        homeV3.setBackground(new java.awt.Color(0, 0, 0));
        homeV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/alertnusa/assets/emergencyIcon.png"))); // NOI18N
        homeV3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeV)
                .addGap(80, 80, 80)
                .addComponent(homeV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(homeV2)
                .addGap(88, 88, 88)
                .addComponent(homeV3)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeV3)
                    .addComponent(homeV2)
                    .addComponent(homeV1)
                    .addComponent(homeV))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALERTNUSA");

        jPanel11.setBackground(new java.awt.Color(29, 151, 165));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kontak Darurat");

        jPanelTema1.setBackground(new java.awt.Color(40, 40, 56));

        labelJudul1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        labelJudul1.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul1.setText("List Kontak Darurat:");

        labelDeskripsi1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        labelDeskripsi1.setForeground(new java.awt.Color(255, 255, 255));
        labelDeskripsi1.setText("+6285737231626 (Prabowo)");

        javax.swing.GroupLayout jPanelTema1Layout = new javax.swing.GroupLayout(jPanelTema1);
        jPanelTema1.setLayout(jPanelTema1Layout);
        jPanelTema1Layout.setHorizontalGroup(
            jPanelTema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTema1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTema1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelDeskripsi1))
                    .addComponent(labelJudul1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTema1Layout.setVerticalGroup(
            jPanelTema1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTema1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDeskripsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelTema1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeV1MouseClicked
        PreparationFrameX prepFrame = new PreparationFrameX();
        prepFrame.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeV1MouseClicked

    private void homeVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeVMouseClicked
        DashboardFrameX dashboardFrame = new DashboardFrameX();
        dashboardFrame.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeVMouseClicked

    private void homeV2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeV2MouseClicked
        EvacuationFrameX EvacFrame = new EvacuationFrameX();
        EvacFrame.setVisible(true);

        // 2. Menutup halaman DashboardFrameX saat ini agar layarnya tidak menumpuk
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_homeV2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println("HALO! SAYA SEDANG DIJALANKAN!"); 
    
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(() -> new SOSFrameX().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeV;
    private javax.swing.JLabel homeV1;
    private javax.swing.JLabel homeV2;
    private javax.swing.JLabel homeV3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTema1;
    private javax.swing.JLabel labelDeskripsi1;
    private javax.swing.JLabel labelJudul1;
    // End of variables declaration//GEN-END:variables
}
