/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.alertnusa.view;
import java.sql.*;
import com.alertnusa.util.DatabaseConnection;
/**
 *
 * @author edy
 */
public class TambahKatalogDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahKatalogDialog.class.getName());

    private admKontenPanel parentPanel;
    /**
     * Creates new form TambahKatalogDialog
     */
    
    public TambahKatalogDialog(java.awt.Frame parent, boolean modal, admKontenPanel parentPanel) {
        super(parent, modal);
        initComponents();
        this.parentPanel = parentPanel;
        
        this.getContentPane().setBackground(new java.awt.Color(40, 40, 56));


        // Setup visual tambahan agar auto-wrap text & rapi
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setWrapStyleWord(true);
        txtPreparation.setLineWrap(true);
        txtPreparation.setWrapStyleWord(true);

        // Muncul tepat di tengah layar frame induk
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        txtNamaBencana = new javax.swing.JTextField();
        txtNamaBencana1 = new javax.swing.JLabel();
        txtNamaBencana2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreparation = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("TAMBAH KATALOG BENCANA");

        jLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Nama Bencana");

        txtNamaBencana1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtNamaBencana1.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaBencana1.setText("Deskripsi");

        txtNamaBencana2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtNamaBencana2.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaBencana2.setText("Langkah Mitigasi");

        txtPreparation.setColumns(20);
        txtPreparation.setRows(5);
        jScrollPane1.setViewportView(txtPreparation);

        btnSimpan.setBackground(new java.awt.Color(0, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnBatal.setBackground(new java.awt.Color(255, 0, 51));
        btnBatal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNamaBencana2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNamaBencana)
                        .addGap(180, 180, 180))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaBencana1)
                            .addComponent(jLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(44, 44, 44)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaBencana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNamaBencana1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaBencana2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNamaBencana.getText().trim();
        String deskripsi = txtDeskripsi.getText().trim();
        String prep = txtPreparation.getText().trim();

        // Validasi input wajib
        if (nama.isEmpty() || deskripsi.isEmpty() || prep.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Semua kolom input wajib diisi, tidak boleh kosong!",
                    "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String query = "INSERT INTO disasters (disaster_name, description, category, risk_level) VALUES (?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(query)) {

            // 1. Isi parameter sesuai urutan tanda tanya (?)
            ps.setString(1, nama);
            ps.setString(2, deskripsi);

            // Untuk kolom ENUM category, kita set default 'natural' (bencana alam). 
            // (Bisa abang ganti jadi 'non_natural' atau 'social' sesuai kebutuhan form desainer nanti)
            ps.setString(3, "natural");

            // Untuk kolom ENUM risk_level, kita set default 'medium'.
            // (Bisa juga disesuaikan menjadi 'low' atau 'high')
            ps.setString(4, "medium");

            int hasil = ps.executeUpdate();
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Katalog bencana baru berhasil ditambahkan!",
                        "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Refresh list katalog di panel admin utama secara live lewat jembatan abang
                if (parentPanel != null) {
                    parentPanel.loadDataAdmin(); // Memicu refresh data katalog secara aman
                }

                // Tutup pop-up dialog
                this.dispose();
            }

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan ke database: " + e.getMessage(),
                    "Error Database", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // Klik kanan btnBatal -> Events -> Action -> actionPerformed
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                TambahKatalogDialog dialog = new TambahKatalogDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtNamaBencana;
    private javax.swing.JLabel txtNamaBencana1;
    private javax.swing.JLabel txtNamaBencana2;
    private javax.swing.JTextArea txtPreparation;
    // End of variables declaration//GEN-END:variables
}
